################## spacefox Main Config ##################
##########################################################

# URLs have to be filled without any protocol "http:// or https://"

## Site Generals ##
###################
root_folder : "/spacefox"
domain      : "alex.dev"

## MySQL DB settings ##
#######################

# enable spacefox & client database
db_enable : false

db_host  : "127.0.0.1"
db_port  : "3306"
db_user  : "root"
db_pass  : ""

db_name  : "spacefox_test"

## Routes / URL rewriting settings ##
#####################################

# Routes - Views settings
route_views :
   "/"     : "home"
   "/test" : "test"

# Routes - Api settings
route_api :
  "/api/hello"     : "test_api => dosomething"
  "/api/readmodel" : "test_api => retrievedb"

# Debug Enable
debug    : false
